-- TASK 1 :
-- Write an SQL query to find top 5 products by revenue. (As per data available, doing TOP 5 product IDs)
SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS TOTALSALES
FROM SALES_DATA GROUP BY PRODUCT_ID ORDER BY SUM(SALES_AMOUNT)DESC;

SELECT *
FROM (
    SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS total_revenue
    FROM SALES_DATA
    GROUP BY PRODUCT_ID
    ORDER BY SUM(SALES_AMOUNT) DESC
)
WHERE ROWNUM <= 5;

-- TASK 2:
-- Calculate monthly total sales and total quantity sold
SELECT 
    TRUNC(SALE_DATE, 'MM') AS MONTH,
    SUM(SALES_AMOUNT) AS TOTAL_SALES,
    SUM(QUANTITY_SOLD) AS TOTAL_QUANTITY
FROM SALES_DATA
GROUP BY TRUNC(SALE_DATE, 'MM')
ORDER BY MONTH;

-- TASK 3:
-- Find average order value by region
SELECT ROUND(AVG(SALES_AMOUNT), 2) AS AVERAGE_SALES, REGION FROM SALES_DATA GROUP BY REGION;

-- TASK 4:
-- Identify customers who has placed more than 3 orders.
SELECT SALES_REP, COUNT(PRODUCT_ID) AS ORDER_COUNT FROM SALES_DATA
GROUP BY SALES_REP
HAVING COUNT(PRODUCT_ID) >3;

--TASK 5:
-- Get percentage contribution of each category to total revenue.   
SELECT PRODUCT_CATEGORY, SUM(SALES_AMOUNT) AS CATEGORY_SALES
FROM SALES_DATA GROUP BY PRODUCT_CATEGORY;

SELECT 
    PRODUCT_CATEGORY,
    SUM(SALES_AMOUNT) AS category_revenue,
    ROUND((SUM(SALES_AMOUNT) / SUM(SUM(SALES_AMOUNT)) OVER ()) * 100, 2) AS percentage_contribution
FROM 
    SALES_DATA
GROUP BY 
    PRODUCT_CATEGORY;


